spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/app-web"
    username: postgres
    password: postgres

security:
  enable-csrf: false

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
